apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: clusters.stolon.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stolon.io
  scope: Namespaced
  names:
    plural: clusters
    singular: cluster
    kind: Cluster
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      subresources:
        status: { }
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
                - keeper
                - proxy
                - sentinel
              properties:
                backups:
                  type: object
                  properties:
                    s3:
                      type: object
                      properties:
                        bucket:
                          type: string
                        prefix:
                          type: string
                        region:
                          type: string
                image:
                  type: string
                keeper:
                  type: object
                  properties:
                    replicas:
                      type: integer
                proxy:
                  type: object
                  properties:
                    replicas:
                      type: integer
                sentinel:
                  type: object
                  properties:
                    replicas:
                      type: integer
                storage:
                  type: object
                  properties:
                    size:
                      type: string
